"""Make the /usr/bin/pip* scripts which honor the distro wheels."""

TEMPLATE = """\
#!{shebang}
# GENERATED BY DEBIAN

# -*- coding: utf-8 -*-
import re
import sys

from pip._internal import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
"""

# This is a one-off script, so just do stupid simple argument parsing.

import sys

substitutions = dict(
    shebang=sys.argv[1],
    )

output_file = sys.argv[2]
with open(output_file, 'w', encoding='utf-8') as fp:
    print(TEMPLATE.format(**substitutions), end='', file=fp)
